let heroList = [{
        "name": '亚托克斯',
        "level": 3,
    },
    {
        "name": '布兰德：',
        "level": 4,
    },
    {
        "name": '伊莉丝',
        "level": 1,
    },
    {
        "name": '伊芙琳',
        "level": 3
    },
    {
        "name": "莫甘娜",
        "level": 3
    }, {
        "name": "韦鲁斯",
        "level": 2
    }, {
        "name": "阿狸",
        "level": 2
    }, {
        "name": "奈德丽",
        "level": 1
    }, {
        "name": "雷恩加尔",
        "level": 3
    }, {
        "name": "沃里克",
        "level": 1
    }, {
        "name": "阿卡丽",
        "level": 4
    }, {
        "name": "凯南",
        "level": 3
    }, {
        "name": "慎",
        "level": 2
    }, {
        "name": "劫",
        "level": 2
    }, {
        "name": "艾尼维亚",
        "level": 5
    }, {
        "name": "艾希",
        "level": 3
    }, {
        "name": "布隆",
        "level": 2
    }, {
        "name": "丽桑卓",
        "level": 2
    }, {
        "name": "瑟庄妮",
        "level": 4
    }, {
        "name": "沃利贝尔",
        "level": 3
    }, {
        "name": "龙王",
        "level": 4
    }, {
        "name": "希瓦娜",
        "level": 3
    }, {
        "name": "布里茨",
        "level": 2
    }, {
        "name": "科加斯",
        "level": 4
    }, {
        "name": "卡萨丁",
        "level": 1
    }, {
        "name": "卡兹克",
        "level": 1
    }, {
        "name": "雷克塞",
        "level": 2
    }, {
        "name": "德莱厄斯",
        "level": 1
    }, {
        "name": "德莱文",
        "level": 4
    }, {
        "name": "卡特琳娜",
        "level": 3
    }, {
        "name": "斯维因",
        "level": 5
    }, {
        "name": "菲奥娜",
        "level": 1
    }, {
        "name": "盖伦",
        "level": 1
    }, {
        "name": "凯尔",
        "level": 5
    }, {
        "name": "蕾欧娜",
        "level": 4
    }, {
        "name": "卢锡安",
        "level": 2
    }, {
        "name": "薇恩",
        "level": 1
    }, {
        "name": "璐璐",
        "level": 2
    }, {
        "name": "波比",
        "level": 3
    }, {
        "name": "崔丝塔娜",
        "level": 1
    }, {
        "name": "维迦",
        "level": 3
    }, {
        "name": "纳尔",
        "level": 4
    }, {
        "name": "普朗克",
        "level": 3
    }, {
        "name": "格雷福斯",
        "level": 1
    }, {
        "name": "厄运小姐",
        "level": 5
    }, {
        "name": "派克",
        "level": 2
    }, {
        "name": "卡尔萨斯",
        "level": 5
    }, {
        "name": "千珏",
        "level": 4
    }, {
        "name": "莫德凯撒",
        "level": 1
    }, {
        "name": "亚索",
        "level": 5
    }, {
        "name": "卡牌大师",
        "level": 2
    }, {
        "name": "蔚",
        "level": 3
    }, {
        "name": "杰斯",
        "level": 2
    }, {
        "name": "金克斯",
        "level": 4
    }, {
        "name": "卡蜜尔",
        "level": 1
    }
]

export {heroList}